"""Complete schema with policy terms and enhanced models

Revision ID: 1aa9ceb7ea31
Revises: 
Create Date: 2025-12-20 13:08:24.531113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa9ceb7ea31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=True),
    sa.Column('policy_name', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('annual_limit', sa.Float(), nullable=True),
    sa.Column('per_claim_limit', sa.Float(), nullable=True),
    sa.Column('family_floater_limit', sa.Float(), nullable=True),
    sa.Column('consultation_limit', sa.Float(), nullable=True),
    sa.Column('diagnostic_limit', sa.Float(), nullable=True),
    sa.Column('pharmacy_limit', sa.Float(), nullable=True),
    sa.Column('dental_limit', sa.Float(), nullable=True),
    sa.Column('vision_limit', sa.Float(), nullable=True),
    sa.Column('alternative_medicine_limit', sa.Float(), nullable=True),
    sa.Column('consultation_copay', sa.Float(), nullable=True),
    sa.Column('network_discount', sa.Float(), nullable=True),
    sa.Column('branded_drugs_copay', sa.Float(), nullable=True),
    sa.Column('initial_waiting_period', sa.Integer(), nullable=True),
    sa.Column('pre_existing_waiting_period', sa.Integer(), nullable=True),
    sa.Column('maternity_waiting_period', sa.Integer(), nullable=True),
    sa.Column('exclusions', sa.JSON(), nullable=True),
    sa.Column('covered_services', sa.JSON(), nullable=True),
    sa.Column('network_providers', sa.JSON(), nullable=True),
    sa.Column('specific_ailment_waiting', sa.JSON(), nullable=True),
    sa.Column('minimum_claim_amount', sa.Float(), nullable=True),
    sa.Column('submission_timeline_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_terms_id'), 'policy_terms', ['id'], unique=False)
    op.create_index(op.f('ix_policy_terms_policy_id'), 'policy_terms', ['policy_id'], unique=True)
    op.create_table('policy_holders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_holder_id', sa.String(), nullable=True),
    sa.Column('policy_holder_name', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('policy_terms_id', sa.String(), nullable=True),
    sa.Column('policy_status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='policystatus'), nullable=True),
    sa.Column('policy_start_date', sa.DateTime(), nullable=True),
    sa.Column('waiting_period_completed', sa.Boolean(), nullable=True),
    sa.Column('annual_limit', sa.Float(), nullable=True),
    sa.Column('annual_limit_used', sa.Float(), nullable=True),
    sa.Column('family_floater_limit', sa.Float(), nullable=True),
    sa.Column('pre_existing_conditions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_terms_id'], ['policy_terms.policy_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_holders_id'), 'policy_holders', ['id'], unique=False)
    op.create_index(op.f('ix_policy_holders_policy_holder_id'), 'policy_holders', ['policy_holder_id'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('policy_holder_id', sa.String(), nullable=True),
    sa.Column('policy_holder_name', sa.String(), nullable=True),
    sa.Column('treatment_date', sa.DateTime(), nullable=True),
    sa.Column('treatment_type', sa.String(), nullable=True),
    sa.Column('treatment_category', sa.String(), nullable=True),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('provider_type', sa.String(), nullable=True),
    sa.Column('provider_network', sa.Boolean(), nullable=True),
    sa.Column('doctor_name', sa.String(), nullable=True),
    sa.Column('doctor_registration_number', sa.String(), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('claimed_amount', sa.Float(), nullable=True),
    sa.Column('eligible_amount', sa.Float(), nullable=True),
    sa.Column('co_payment_amount', sa.Float(), nullable=True),
    sa.Column('network_discount_amount', sa.Float(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('deductions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'PARTIAL', 'MANUAL_REVIEW', name='decisiontype'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('rejection_reasons', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('submission_delay_days', sa.Integer(), nullable=True),
    sa.Column('fraud_indicators', sa.JSON(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('manual_review_reason', sa.String(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_holder_id'], ['policy_holders.policy_holder_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_id'), 'claims', ['claim_id'], unique=True)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_claims_policy_holder_id'), 'claims', ['policy_holder_id'], unique=False)
    op.create_table('dependents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dependent_id', sa.String(), nullable=True),
    sa.Column('policy_holder_id', sa.String(), nullable=True),
    sa.Column('dependent_name', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_holder_id'], ['policy_holders.policy_holder_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependents_dependent_id'), 'dependents', ['dependent_id'], unique=True)
    op.create_index(op.f('ix_dependents_id'), 'dependents', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_legible', sa.Boolean(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('manual_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('original_decision', sa.String(), nullable=True),
    sa.Column('final_decision', sa.String(), nullable=True),
    sa.Column('reason_for_review', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_reviews_id'), 'manual_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_reviews_id'), table_name='manual_reviews')
    op.drop_table('manual_reviews')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_dependents_id'), table_name='dependents')
    op.drop_index(op.f('ix_dependents_dependent_id'), table_name='dependents')
    op.drop_table('dependents')
    op.drop_index(op.f('ix_claims_policy_holder_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_policy_holders_policy_holder_id'), table_name='policy_holders')
    op.drop_index(op.f('ix_policy_holders_id'), table_name='policy_holders')
    op.drop_table('policy_holders')
    op.drop_index(op.f('ix_policy_terms_policy_id'), table_name='policy_terms')
    op.drop_index(op.f('ix_policy_terms_id'), table_name='policy_terms')
    op.drop_table('policy_terms')
    # ### end Alembic commands ###
