"""Add claim_decisions table for adjudication

Revision ID: 4b895a667b0b
Revises: create_usage_log
Create Date: 2025-12-22 09:13:19.533579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b895a667b0b'
down_revision: Union[str, Sequence[str], None] = 'create_usage_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'PARTIAL', 'MANUAL_REVIEW', name='decisiontype'), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('original_amount', sa.Float(), nullable=True),
    sa.Column('rejection_reasons', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('eligibility_passed', sa.Boolean(), nullable=True),
    sa.Column('documents_valid', sa.Boolean(), nullable=True),
    sa.Column('coverage_verified', sa.Boolean(), nullable=True),
    sa.Column('limits_ok', sa.Boolean(), nullable=True),
    sa.Column('medically_necessary', sa.Boolean(), nullable=True),
    sa.Column('fraud_indicators', sa.JSON(), nullable=True),
    sa.Column('copay_amount', sa.Float(), nullable=True),
    sa.Column('copay_percentage', sa.Float(), nullable=True),
    sa.Column('sub_limit_applied', sa.String(), nullable=True),
    sa.Column('annual_limit_remaining', sa.Float(), nullable=True),
    sa.Column('adjudicated_at', sa.DateTime(), nullable=True),
    sa.Column('adjudicated_by', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_decisions_claim_id'), 'claim_decisions', ['claim_id'], unique=True)
    op.create_index(op.f('ix_claim_decisions_id'), 'claim_decisions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_decisions_id'), table_name='claim_decisions')
    op.drop_index(op.f('ix_claim_decisions_claim_id'), table_name='claim_decisions')
    op.drop_table('claim_decisions')
    # ### end Alembic commands ###
