"""add_auth_fields_to_policy_holders

Revision ID: ddcae578c358
Revises: 0f41c72099fc
Create Date: 2025-12-22 12:22:34.728254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcae578c358'
down_revision: Union[str, Sequence[str], None] = '0f41c72099fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip the claims.decision enum conversion - it's already correct
    op.add_column('policy_holders', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('policy_holders', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_policy_holders_email'), 'policy_holders', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_holders_email'), table_name='policy_holders')
    op.drop_column('policy_holders', 'is_active')
    op.drop_column('policy_holders', 'hashed_password')
    # ### end Alembic commands ###
